var arrayNombres = new Array();
arrayNombres.push("adrvapor");
arrayNombres.push("SrAleSelz");
arrayNombres.push("AlbertoRayo");
arrayNombres.push("It'sGonza :D");
arrayNombres.push("Mokito");
arrayNombres.push("Shofiris");
arrayNombres.push("Whiite");
arrayNombres.push("Shelby");
arrayNombres.push("Neji");
arrayNombres.push("Pijama Games");

var arrayCausaMuerte = new Array();
arrayCausaMuerte.push("Se cayó por las\nescaleras de la\ncafetería de la\nuniversidad");
arrayCausaMuerte.push("Sufrió un derrame\ncerebral tras\njugar 453 horas\nseguidas al Isaac");
arrayCausaMuerte.push("Fue el sacrificio\npara la invocación\nde un dios primigenio");
arrayCausaMuerte.push("Murió apuñalado\npor la espalda\npor un villero");
arrayCausaMuerte.push("Muerte por triple\nmortal.\nAhora ya sabe por qué\nse llama así");
arrayCausaMuerte.push("Cayó por un acantilado\npor exceso de velocidad\nen una motocicleta");
arrayCausaMuerte.push("Sacó un 1 de natural\nen DnD");
arrayCausaMuerte.push("Murió por comer kebab\nmientras saltaba\nal hiperespacio");
arrayCausaMuerte.push("Broncoaspiración por\nvómito");
arrayCausaMuerte.push("Murió haciendo lo que\nmás disfrutaba,\ndurmiendo");